# Generated by Django 4.0.3 on 2022-03-28 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='phone_number',
            field=models.CharField(default='000-000-0000', max_length=12),
        ),
    ]
