# Generated by Django 4.0.3 on 2022-04-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0002_extendeduser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Camera', max_length=25)),
                ('RTSPurl', models.CharField(default='cam.com', max_length=300)),
                ('camera', models.CharField(choices=[('wyze', 'WYZE'), ('sonoff', 'SONOFF')], default='wyze', max_length=10)),
            ],
        ),
    ]
