# Generated by Django 4.0.3 on 2022-04-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0002_extendeduser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='notification_interval',
            field=models.CharField(choices=[('immediately', 'immediate'), ('daily', 'daily'), ('weekly', 'weekly')], default='weekly', max_length=11),
        ),
    ]
