# Generated by Django 4.0.3 on 2022-04-18 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0003_cam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cam',
        ),
    ]
