# Generated by Django 4.0.3 on 2022-05-04 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0003_extendeduser_notification_interval'),
        ('start', '0004_delete_cam'),
    ]

    operations = [
    ]
