# Generated by Django 3.2.5 on 2022-05-04 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0003_extendeduser_notification_interval'),
        ('start', '0004_delete_cam'),
    ]

    operations = [
    ]
