# Generated by Django 3.2.5 on 2022-05-05 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0007_extendeduser_latest_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='latest_update',
            field=models.DateField(default=datetime.date(2022, 5, 5), null=True),
        ),
    ]
