# Generated by Django 3.2.5 on 2022-05-06 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0008_alter_extendeduser_latest_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extendeduser',
            old_name='latest_update',
            new_name='latest_notify',
        ),
    ]
