# Generated by Django 3.2.5 on 2022-05-06 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0009_rename_latest_update_extendeduser_latest_notify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='latest_notify',
            field=models.DateField(default=datetime.date(2022, 5, 6), null=True),
        ),
    ]
