# Generated by Django 3.2.5 on 2022-05-06 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0005_merge_20220504_0122'),
        ('start', '0010_alter_extendeduser_latest_notify'),
    ]

    operations = [
    ]
