# Generated by Django 4.0.3 on 2022-03-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simple',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='simple',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
