# Generated by Django 4.0.3 on 2022-03-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_simple_image_alter_simple_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Simple',
        ),
    ]
