# Generated by Django 4.0.3 on 2022-03-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0004_camera_rename_text_image_name_image_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
