# Generated by Django 4.0.3 on 2022-03-30 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0007_camera_rtsp_url_camera_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='camera',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='camera.camera'),
            preserve_default=False,
        ),
    ]
