# Generated by Django 4.0.3 on 2022-04-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0009_alter_camera_name_alter_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='camera',
            field=models.CharField(choices=[('wyze', 'WYZE'), ('sonoff', 'SONOFF')], default='wyze', max_length=10),
        ),
    ]
