# Generated by Django 3.2.5 on 2022-05-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0011_alter_image_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
